### ISSUE TITLE
Feed pulls through draft/unpublished articles

### ISSUE THREAD

**Issue by benfurfie** [edalzell/statamic-feed#4]
The addon is currently pulling through unpublished/draft entries from collections.
In theory, it should be checking the published status before buildng the array of items.

**Comment by edalzell** [comment]
@benfurfie can you verify this fixes your issue? Line 59 in `FeedController.php`:
```
        $this->entries = EntryAPI::whereCollection(array_get($config, 'collections', []))
            ->removeUnpublished()
            ->removeFuture()
            ->multisort('date:desc|title:asc')
            ->limit(20);
```
